### ISSUE TITLE
hive context on spark

### ISSUE THREAD

**Issue by avinashnishanh92** [holman/feedback#667]
i have installed spark and hive on the cluster and i am trying to process the file from hdfs

i have added these jars

spark-assembly-1.2.0-cdh5.3.0-hadoop2.5.0-cdh5.3.0​.jar

when i try to proces local file system i have added these jars

spark-assembly-1.2.0-hadoop1.0.4

spark-core_2.10-0.9.0-incubating

and it works fine

 

i am getting this error

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/hiv                             ​                                                  ​         e/conf/HiveConf
        at org.apache.spark.sql.hive.api.java.JavaHiveContext​.<init>(JavaHiveCon                               ​                                                  ​       text.scala:30)
        at max.main(max.java:29)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Nativ​e Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Native​MethodAccessorImpl.                               ​                                                  ​       java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(De​legatingMethodAcces                               ​                                                  ​       sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.launch(SparkS​ubmit.scala:358)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSub​mit.scala:75)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubm​it.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.hive.conf.HiveCon               ​                                                  ​                       f
        at java.net.URLClassLoader$1.run(URLClassLoader.java:​366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:​355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.j​ava:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:4​25)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launche​r.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:3​58)
        ... 9 more

i have added hive config in classpath
please tell me the prequisite to run the program

**Comment by holman** [comment]
Don't know! The spark I wrote is a simple bash script, so different than the Apache project. 'fraid I can't be much help there!
