### ISSUE TITLE
events.js while runing gulp 

### ISSUE THREAD

**Issue by KaranSofat** [holman/feedback#671]
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: File not found with singular glob
    at Glob.<anonymous> (/var/www/frontend/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/index.js:34:30)
    at Glob.EventEmitter.emit (events.js:95:17)
    at Glob._finish (/var/www/frontend/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/glob.js:171:8)
    at done (/var/www/frontend/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/glob.js:158:12)
    at Glob._processSimple2 (/var/www/frontend/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/glob.js:640:12)
    at /var/www/frontend/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/glob.js:628:10
    at Glob._stat2 (/var/www/frontend/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/glob.js:724:12)
    at lstatcb_ (/var/www/frontend/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/glob.js:716:12)
    at RES (/var/www/frontend/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/node_modules/inflight/inflight.js:23:14)
    at f (/var/www/frontend/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/node_modules/once/once.js:17:25)

**Comment by holman** [comment]
Don't know! Ain't use no node.
